services:
  hazelcast1:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast1
    environment:
      - HZ_CLUSTERNAME=dev
      - HZ_NETWORK_PUBLICADDRESS=localhost:5701
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
    ports:
      - "5701:5701"
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/config/hazelcast.xml
    networks:
      - hazelcast-net

  hazelcast2:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast2
    environment:
      - HZ_CLUSTERNAME=dev
      - HZ_NETWORK_PUBLICADDRESS=localhost:5702
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
    ports:
      - "5702:5701"
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/config/hazelcast.xml
    networks:
      - hazelcast-net

  hazelcast3:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast3
    environment:
      - HZ_CLUSTERNAME=dev
      - HZ_NETWORK_PUBLICADDRESS=localhost:5703
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config/hazelcast.xml
    ports:
      - "5703:5701"
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/config/hazelcast.xml
    networks:
      - hazelcast-net

  management-center:
    image: hazelcast/management-center:5.3
    container_name: hazelcast-mancenter
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast1:5701,hazelcast2:5701,hazelcast3:5701
    ports:
      - "8080:8080"
    networks:
      - hazelcast-net
    depends_on:
      - hazelcast1
      - hazelcast2
      - hazelcast3

networks:
  hazelcast-net:
    driver: bridge
